apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target:
      kind: Deployment
      name: demo-app
    patch: |
      - op: replace
        path: /spec/replicas
        value: 1

  - target:
      kind: ConfigMap
      name: demo-app-config
    patch: |
      - op: replace
        path: /data/GREETING
        value: "Hello from INT environment"
      - op: replace
        path: /data/ENV
        value: "int"

commonAnnotations:
  environment: int
