apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infra
  namespace: argocd
spec:
  description: Infrastructure and platform components

  sourceRepos:
    - '*'

  destinations:
    - namespace: platform
      server: '*'
    - namespace: kube-system
      server: '*'

  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
    - group: ''
      kind: ResourceQuota

  namespaceResourceWhitelist:
    - group: ''
      kind: '*'

  orphanedResources:
    warn: true
