apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: whoami-int
    app.kubernetes.io/name: whoami
    app.kubernetes.io/part-of: demo
    env: int
  name: whoami
  namespace: demo-int
spec:
  ports:
  - name: http
    port: 80
    targetPort: http
  selector:
    app.kubernetes.io/name: whoami
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    secret.reloader.stakater.com/reload: whoami-config
  labels:
    app.kubernetes.io/instance: whoami-int
    app.kubernetes.io/name: whoami
    app.kubernetes.io/part-of: demo
    env: int
  name: whoami
  namespace: demo-int
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: whoami
  template:
    metadata:
      labels:
        app.kubernetes.io/name: whoami
    spec:
      containers:
      - args:
        - --port=8080
        - --name=$(WHOAMI_NAME)
        env:
        - name: WHOAMI_NAME
          valueFrom:
            secretKeyRef:
              key: greeting
              name: whoami-config
        image: traefik/whoami:v1.12.0
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 5
          periodSeconds: 10
        name: whoami
        ports:
        - containerPort: 8080
          name: http
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 2
          periodSeconds: 5
        resources:
          limits:
            cpu: 100m
            memory: 64Mi
          requests:
            cpu: 5m
            memory: 16Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 65532
      securityContext:
        seccompProfile:
          type: RuntimeDefault
