apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target:
      kind: ResourceQuota
      name: platform-quota
    patch: |
      - op: replace
        path: /spec/hard/pods
        value: "10"
      - op: replace
        path: /spec/hard/requests.cpu
        value: "1"
      - op: replace
        path: /spec/hard/requests.memory
        value: 1Gi

commonAnnotations:
  environment: int
